name: 'Deploy to AKS'
description: 'Deploy services to AKS'
inputs:
  images:
    description: 'A space-separated list of images to deploy'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Deploy each image
      run: |
        for service in ${{ inputs.images }}; do
          echo "Deploying $service"
          kubectl apply -f kubernetes-manifests/$service.yaml 
          kubectl set image deployment/$service server=$service:latest --namespace ${{ env.AKS_NAMESPACE }}
          echo "Deployed $service"
        done

